Use `TreeSet` instead of `HashSet` due to the unit test fail when running test on other variants of Java Runtime.
This problem occurs because the internal implementation of `HashSet` is not the same in all JDK, tested on Android VM and JVM 11.

See TestExpr#test_args_cnc:
junit.framework.ComparisonFailure: expected:<[x[, x^2]]> but was:<[x[^2, x]]>
at junit.framework.Assert.assertEquals(Assert.java:85)
at junit.framework.Assert.assertEquals(Assert.java:91)
at org.matheclipse.core.sympy.core.TestExpr.test_args_cnc(TestExpr.java:412)