Use TreeSet instead of HashSet due to some unit tests fail when running test on other variants of Java Runtime. (#744)
* Do not use default locale in String#toLowerCase() and String#toUpperCase() since it causes unpredictable behavior in some language.
https://stackoverflow.com/questions/11063102/using-locales-with-javas-tolowercase-and-touppercase

* Cleanup

* testDeterminePrecision

* Fix ApfloatNum bug: `Round(N[0.03306158858189456, 30] * 100, 10^-2) // N`

* Fix ApfloatNum bug: `Round(N[0.03306158858189456, 30] * 100, 10^-2) // N`

* Android: Fix missing intValueExact method in Android SDK

* Use `TreeSet` instead of `HashSet` due to the unit test fail when running test on other variants of Java Runtime.

This problem occurs because the internal implementation of `HashSet` is not the same in all JDK, tested on Android VM and JVM 11.

See TestExpr#test_args_cnc:
junit.framework.ComparisonFailure: expected:<[x[, x^2]]> but was:<[x[^2, x]]>
at junit.framework.Assert.assertEquals(Assert.java:85)
at junit.framework.Assert.assertEquals(Assert.java:91)
at org.matheclipse.core.sympy.core.TestExpr.test_args_cnc(TestExpr.java:412)

---------

Co-authored-by: Duy Tran <mail@duytran.com>
Co-authored-by: duytran <duytranle.it@gmail.com>